### ISSUE TITLE
Feature: Character Has Abilities Scores

### ISSUE THREAD

**Issue by mszmansky** [mszmansky/DandD-TDD#1]
As a character I want to have several abilities so that I am not identical to other characters except in name

Abilities are Strength, Dexterity, Constitution, Wisdom, Intelligence, Charisma
Abilities range from 1 to 20 and default to 10
Abilities have modifiers according to the following table
Score   Modifier    Score   Modifier    Score   Modifier    Score   Modifier
1                -5 6              -2               11        0     16  +3
2   -4  7   -2  12  +1  17  +3
3   -4  8   -1  13  +1  18  +4
4   -3  9   -1  14  +2  19  +4
5   -3  10  0   15  +2  20  +5

**Comment by jsmith9090** [comment]
Mike - Just curious as to why the ability needs to know what type it is?
