### ISSUE TITLE
A weapon should be either one or two-handed

### ISSUE THREAD

**Issue by mszmansky** [mszmansky/DandD-TDD#22]
A character can use one two handed weapon and not carry a shield.  If they are using a one handed weapon then they may carry a shield.  

A character cannot carry two one-handed weapons.

**Comment by lenharding** [comment]
Booooo. Need to be able to carry two one handed weapons! Defense through offense.

**Comment by mszmansky** [comment]
Still need to implement character using a one handed weapon when using a shield and no shield when using a two-handed weapon
